sudo: false
language: python
python: 3.5

matrix:
  include:
    - python: 2.6
    - python: 2.7
    - python: 3.5
    - python: 3.6
  fast_finish: true
  allow_failures:
    - python: 2.6

cache:
  apt: true
  ccache: true
  pip: true
  directories:
    - $HOME/.cache
addons:
  apt_packages:
    - ccache
    - libssl-dev

install:
  - pip install --upgrade pip setuptools coverage codecov nose
script:
  - script/test python$TRAVIS_PYTHON_VERSION
  - codecov --flags python$TRAVIS_PYTHON_VERSION
