sudo: false
language: python

matrix:
  fast_finish: true
  include:
    # - {python: 3.5, env: TOXENV=pep8}
    - {python: 2.7}
    - {python: 3.3}
    - {python: 3.4}
    - {python: 3.5}
    - {python: 3.6}
    - {python: pypy}

cache:
  apt: true
  ccache: true
  pip: true
  directories:
    - $HOME/.cache
addons:
  apt_packages:
    # - libssl-dev

install:
  # - pip install --upgrade pip setuptools tox virtualenv codecov
  - pip install --upgrade pip setuptools codecov
script:
  - virtualenv=0 script/test -sv
  - codecov --flags=$(echo $python |tr -d -- '-.')
# after_failure:
#   - for X in .tox/$TOXENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
#   - echo "pip.log\n"; cat $HOME/.pip/pip.log
